<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-UH2GJC7" failures="2" tests="2" name="com.codingiri.TestNG_Test.First_Ebayhome_sanity" time="78.466" errors="0" timestamp="15 Jul 2021 06:35:59 GMT" skipped="0">
  <testcase classname="com.codingiri.TestNG_Test.First_Ebayhome_sanity" name="Empty_Search_Test_softAssert" time="60.394">
    <failure message="The following asserts failed:
	verify the url of new page expected [] but found [https://www.ebay.com/n/all-categories]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
verify the url of new page expected [] but found [https://www.ebay.com/n/all-categories]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.codingiri.TestNG_Test.First_Ebayhome_sanity.Empty_Search_Test_softAssert(First_Ebayhome_sanity.java:143)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- Empty_Search_Test_softAssert -->
  <testcase classname="com.codingiri.TestNG_Test.First_Ebayhome_sanity" name="Empty_Search_Test" time="18.072">
    <failure message="Shop by Category | eBay expected [null] but found [https://www.ebay.com/n/all-categories]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Shop by Category | eBay expected [null] but found [https://www.ebay.com/n/all-categories]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotSame(Assert.java:772)
at org.testng.Assert.assertNull(Assert.java:708)
at com.codingiri.TestNG_Test.First_Ebayhome_sanity.Empty_Search_Test(First_Ebayhome_sanity.java:75)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- Empty_Search_Test -->
</testsuite> <!-- com.codingiri.TestNG_Test.First_Ebayhome_sanity -->
